{{ if .Values.ombi.enabled }}
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: {{ .Release.Name }}-ombi.{{ .Values.dns_domain }}
spec:
  routes:
    - match: Host(`{{ .Release.Name }}-ombi.{{ .Values.dns_domain }}`)
      kind: Rule
      services:
        - name: ombi
          kind: Service
          port: 5000
      middlewares:
        - name: error-pages
          namespace: traefik
{{ end }}