{{ if .Values.mattermost.enabled }}
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: {{ .Release.Name }}-mattermost.{{ .Values.dns_domain }}
spec:
  routes:
    - match: Host(`{{ .Release.Name }}-mattermost.{{ .Values.dns_domain }}`)
      kind: Rule
      services:
        - name: mattermost
          kind: Service
          port: 8065
      middlewares:
        - name: error-pages
          namespace: traefik
{{ end }}