{{ if .Values.seafile.enabled }}
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: {{ .Release.Name }}-seafile.{{ .Values.dns_domain }}
spec:
  routes:
    - match: Host(`{{ .Release.Name }}-seafile.{{ .Values.dns_domain }}`)
      kind: Rule
      services:
        - name: seafile
          kind: Service
          port: 80
      middlewares:    
        - name: error-pages
          namespace: traefik
{{ end }}