{{ if .Values.rdtclientpremiumize.enabled }}
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: {{ .Release.Name }}-rdtclient-premiumize.{{ .Values.dns_domain }}
spec:
  routes:
    - match: Host(`{{ .Release.Name }}-rdtclient-premiumize.{{ .Values.dns_domain }}`)
      kind: Rule
      services:
        - name: rdtclient-premiumize
          kind: Service
          port: 6500
      middlewares:  
        - name: {{ .Release.Name }}-traefik-forward-auth
        - name: error-pages
          namespace: traefik
{{ end }}