{{ if .Values.notifiarr.enabled }}
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: {{ .Release.Name }}-notifiarr.{{ .Values.dns_domain }}
spec:
  routes:
    - match: Host(`{{ .Release.Name }}-notifiarr.{{ .Values.dns_domain }}`) && PathPrefix(`/api/`)
      kind: Rule
      services:
        - name: notifiarr
          kind: Service
          port: 5454      
    - match: Host(`{{ .Release.Name }}-notifiarr.{{ .Values.dns_domain }}`) && PathPrefix(`/plex/`)
      kind: Rule
      services:
        - name: notifiarr
          kind: Service
          port: 5454      
    - match: Host(`{{ .Release.Name }}-notifiarr.{{ .Values.dns_domain }}`)
      kind: Rule
      services:
        - name: notifiarr
          kind: Service
          port: 5454
      middlewares:
        - name: {{ .Release.Name }}-traefik-forward-auth
        - name: {{ .Release.Name }}-add-x-webauth-user
{{ end }}

