{{ if .Values.jackett.enabled }}
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: {{ .Release.Name }}-jackett.{{ .Values.dns_domain }}
spec:
  routes:
    - match: Host(`{{ .Release.Name }}-jackett.{{ .Values.dns_domain }}`)
      kind: Rule
      services:
        - name: jackett
          kind: Service
          port: 9117
      middlewares:  
        - name: {{ .Release.Name }}-traefik-forward-auth
        - name: error-pages
          namespace: traefik
    - match: Host(`{{ .Release.Name }}-jackett.{{ .Values.dns_domain }}`) && PathPrefix(`/api/`)
      kind: Rule
      services:
        - name: jackett
          kind: Service
          port: 9117
    - match: Host(`{{ .Release.Name }}-jackett.{{ .Values.dns_domain }}`) && PathPrefix(`/dl/`)
      kind: Rule
      services:
        - name: jackett
          kind: Service
          port: 9117
{{ end }}