{{ if .Values.mongoexpress.enabled }}
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: {{ .Release.Name }}-mongoexpress.{{ .Values.dns_domain }}
spec:
  routes:
    - match: Host(`{{ .Release.Name }}-mongoexpress.{{ .Values.dns_domain }}`)
      kind: Rule
      services:
        - name: mongoexpress
          kind: Service
          port: 8081
      middlewares:  
        - name: {{ .Release.Name }}-traefik-forward-auth
        - name: error-pages
          namespace: traefik
{{ end }}