{{ if .Values.shoko.enabled }}
{{ if .Values.volsync.enabled }}
apiVersion: volsync.backube/v1alpha1
kind: ReplicationSource
metadata:
  name: rs-config-shoko-ssd
spec:
  sourcePVC: config-shoko-ssd
  trigger:
    schedule: "0 {{ mod .Values.userId 24 }} * * *"
  restic:
    pruneIntervalDays: 7
    repository: config-shoko-ssd-volsync-restic-config
    retain:
      daily: 2
    copyMethod: Snapshot
    moverAffinity:
      podAffinity:
        requiredDuringSchedulingIgnoredDuringExecution: 
        - labelSelector:
            matchExpressions:
            - key: app.elfhosted.com/name
              operator: In
              values:
              - zurg
          topologyKey: "kubernetes.io/hostname"
    cacheCapacity: 1Gi
    cacheStorageClassName: topolvm-provisioner-thin
    cacheAccessModes:
    - ReadWriteOnce    
    volumeSnapshotClassName: {{ .Values.storageclass.rwx.volumeSnapshotClassName }}
{{ end }}
{{ end }}