{{ if or .Values.zurg.enabled .Values.zurgplus.enabled .Values.zurghobbit.enabled }}
{{ if .Values.volsync.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: config-zurg-ssd-volsync-restic-config
type: Opaque
stringData:
  RESTIC_REPOSITORY: s3:{{ .Values.volsync.restic_repository }}/volsync/{{ .Release.Namespace }}/config-zurg-ssd
  RESTIC_PASSWORD: {{ .Values.volsync.restic_password }}
  AWS_ACCESS_KEY_ID: {{ .Values.volsync.aws_access_key_id }}
  AWS_SECRET_ACCESS_KEY: {{ .Values.volsync.aws_secret_access_key }}
{{ end }}
{{ end }}