{{- if and .Values.notifiarr.enabled .Values.volsync.enabled }}
{{- if .Values.location.enabled }}
apiVersion: volsync.backube/v1alpha1
kind: ReplicationDestination
metadata:
  name: rd-config-notifiarr-ssd
  annotations:
    helm.sh/hook: pre-install,pre-upgrade  
spec:
  trigger:
    manual: runonce
  restic:
    repository: config-notifiarr-ssd-volsync-restic-config
    copyMethod: Snapshot
    moverAffinity:
      podAffinity:
        requiredDuringSchedulingIgnoredDuringExecution: 
        - labelSelector:
            matchExpressions:
            - key: app.elfhosted.com/name
              operator: In
              values:
              - zurg
          topologyKey: "kubernetes.io/hostname"
    cacheCapacity: 1Gi
    capacity: 1Gi
    cacheStorageClassName: topolvm-provisioner-thin
    accessModes:
    - {{ .Values.storageclass.rwx.accessMode }}
    storageClassName: {{ .Values.storageclass.rwx.name }}
    cacheAccessModes:
    - ReadWriteOnce
    volumeSnapshotClassName: {{ .Values.storageclass.rwx.volumeSnapshotClassName }}
{{- end }}
{{- end }}