{{ if .Values.wizarr.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: wizarr-steps-jellyfin
data:
  01_download.md: |
    ---
    title: "Join & download Jellyfin"
    require: true
    ---

    ## {{ _("You're in! ğŸ‰") }}

    {{ _("Great news! You've been granted access to {{ .Release.Name }}'s **ElfHosted Jellyfin Server**! ğŸ¥³") }}

  02_about.md: |
    ---
    title: "What is Jellyfin?"
    ---

    ## â„¹ï¸ {{ _("What's Jellyfin?") }}

    {{ _("Jellyfin lets people share their film and TV libraries with friends. "
          "You're here because {{ .Release.Name }}â€™s invited you to theirs! ğŸ“º") }}

    ## ğŸ¿ {{ _("How do I watch stuff?") }}

    Search your phone, tablet, computer or smart-TV's app store for "Jellyfin", or [{{ _("download on this device") }}](https://jellyfin.org/downloads){target=_blank .btn}.

    {{ _("Sign in, search, push play. Thatâ€™s it!") }}

  03_requests.md: |
    ---
    title:  "Automatic requests"
    requires: [overseerr_url]
    ---

    ### {{ _("Request mooar content ğŸ™‹â€â™€ï¸") }}

    {{ _("Canâ€™t find what you want to watch? Make a request â€” robots will grab the film or episode automatically and add it to the library.") }}

    [{{ _("Make a request") }}]({{ overseerr_url }}){:target=_blank .btn}

  04_discord.md: |
    ---
    title:  "Discord community"
    requires: [discord_id]
    ---

    <iframe src="https://discord.com/widget?id={{ discord_id }}&theme=dark"
            width="350" height="500"
            allowtransparency="true" frameborder="0"
            sandbox="allow-popups allow-same-origin allow-scripts"></iframe>

  05_tips.md: |
    ---
    title: "Tips for the best experience"
    ---

    ## ğŸ {{ _("Get the best quality") }}

    {{ _("Plex sometimes defaults to low quality or shows its own adverts first. "
          "Hereâ€™s how to fix that:") }}

    1. **{{ _("Set streaming quality to original") }}** â€“ Settings â†’ Playback  
    2. **{{ _("Enable hardware decoding") }}** if your device supports it for smoother 4K.  
    3. **{{ _("Prefer Ethernet over Wi-Fi") }}** on smart-TVs.

    *Happy viewing!* ğŸ¿

  06_elfhosted.md: |
    ---
    title: "Get ElfHosted!"
    ---

    ## ğŸ {{ _("Want your **own** media library?") }}

    Ready to take it to the next level?

    Get your **own** Media Server with a [{{ _("ElfHosted bundle") }}](https://store.elfhosted.com/product-category/streaming-bundles/){target=_blank .btn}, $1 7-day trials available!

    Rock on! ğŸ¤˜  

{{ end }}