{{ if .Values.homepage.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: config-homepage-ssd
  annotations:
    helm.sh/resource-policy: keep
spec:
{{- $pvc := (lookup "v1" "PersistentVolumeClaim" .Release.Namespace "config-homepage-ssd" ) }}
  {{- if not $pvc }}
  dataSourceRef:
    kind: ReplicationDestination
    apiGroup: volsync.backube
    name: rd-config-homepage-ssd
  {{- end }}
  accessModes:
  - {{ .Values.storageclass.rwx.accessMode }}
  resources:
    requests:
      storage: 1Gi
  storageClassName: {{ .Values.storageclass.rwx.name }}
{{ end }}