{{ if .Values.autoscan.enabled }}
{{ if .Values.volsync.enabled }}
apiVersion: volsync.backube/v1alpha1
kind: ReplicationDestination
metadata:
  name: rd-config-autoscan-ssd
spec:
  trigger:
    manual: runonce
  restic:
    repository: config-autoscan-ssd-volsync-restic-config
    copyMethod: Snapshot
    cacheCapacity: 1Gi
    capacity: 1Gi
    cacheStorageClassName: topolvm-provisioner-thin
    accessModes:
    - {{ .Values.storageclass.rwx.accessMode }}
    storageClassName: {{ .Values.storageclass.rwx.name }}
    cacheAccessModes:
    - ReadWriteOnce
    volumeSnapshotClassName: {{ .Values.storageclass.rwx.volumeSnapshotClassName }}
{{ end }}
{{ end }}