{{ if .Values.mediafusion.enabled }}
apiVersion: "cilium.io/v2"
kind: CiliumNetworkPolicy
metadata:
  name: "permit-mediafusion-egress-mediafusion-redis"
spec:
  endpointSelector:
    matchLabels:
      app.elfhosted.com/name: mediafusion
  egress:
  - toEndpoints:
    - matchLabels:
        k8s:io.kubernetes.pod.namespace: mediafusion
        app.kubernetes.io/name: redis
    toPorts:
      - ports:
        - port: '6379'
          protocol: TCP
{{ end }}