kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: elfterm
subjects:
- kind: ServiceAccount
  name: filebrowser
- kind: ServiceAccount
  name: filebrowser
  namespace: aa-bsm
- kind: ServiceAccount
  name: filebrowser
  namespace: aa-layezeeelf
roleRef:
  kind: Role
  name: kubernetes-dashboard
  apiGroup: rbac.authorization.k8s.io